### ISSUE TITLE
Missing opentelemetry results

### ISSUE THREAD

**Issue by Eomm** [nodesource/node-APMs-benchmark#1]
Reading the repository's source code, it seems that the opentelemetry module has been tested:

https://github.com/nodesource/node-APMs-benchmark/blob/main/agents/opentelemetry.js

but the website does not show them: https://benchmark.nodesource.com/

Would it be valuable to add them?

**Comment by santigimeno** [comment]
First of all, sorry for the delay.
Yes, you're right. We have just updated the site with data for OpenTelemetry and other APM's. Thanks!

**Comment by Eomm** [comment]
Great update so far!
Thank you!
